export const GET_PRODOUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODOUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODOUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const SEARCH = "SEARCH";
export const FILTER = "FILTER";
export const SORT = "SORT";
